server:
  port: 8090

spring:
  mvc.view.prefix: /WEB-INF/view/
  mvc.view.suffix: .jsp

logging:
#  path: c:\temp\
  level:
    org.springframework.web: DEBUG
    com.spring: DEBUG

datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://192.168.0.192:3326/test?useUnicode=true&charaterEncoding=utf-8&interactiveClient=true&autoReconnect=true&autoReconnectForPools=true&useSSL=false
  username: test01
  password: aei12@3$TE
  initial-size: 10
  max-active: 10
  max-idle: 10
  min-idle: 10
  max-wait: 3000
  

