server:
  port: 5000

spring:
  mvc.view.prefix: /WEB-INF/view/
  mvc.view.suffix: .jsp

logging:
#  path: c:\temp\
  level:
    org.springframework.web: DEBUG
    com.spring: DEBUG

datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://ec2-107-22-192-11.compute-1.amazonaws.com:5432/db5n1ro71i1tv?sslmode=require
  username: ueberfgroelzuy
  password: c2b7d39d9545095a10e041f7517e1a4166fdceae619ef9ff4257bc50da2d61e7
  initial-size: 10
  max-active: 10
  max-idle: 10
  min-idle: 10
  max-wait: 3000
